version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  lint:
    executor: 
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    executor: 
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    docker: 
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
    
  deliver-db:
    docker: 
        - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build Dockerfile-db -t domain314/conint_backend_db
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push domain314/conint_backend_db:latest
  deliver-app:
    docker: 
        - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build Dockerfile-app -t domain314/conint_backend
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push domain314/conint_backend:latest
  deploy:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to AWS
          command: |
            # deploy to AWS


workflows:
  version: 2
  build-test-deliver-and-deploy:
    jobs:
      - lint:
          filters:
            branches:
              only: main
      - test:
          requires:
            - lint
          filters:
            branches:
              only: main
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
      - deliver-db:
          requires:
            - build
          filters:
            branches:
              only: main
      - deliver-app:
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - deliver
          filters:
            branches:
              only: main
