version: 2.1
executors:
  node-executor:
    docker:
      - image: node:16
  docker-executor:
    docker:
      - image: docker:24.0.0
jobs:
  lint:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t your-dockerhub-name/your-image-name .
  deliver:
    executor: docker-executor
    steps:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push your-dockerhub-name/your-image-name
  deploy:
    steps:
      - run: # Here, add commands to deploy to AWS using aws cli

workflows:
  version: 2
  build-test-and-deliver:
    jobs:
      - lint:
          filters:
            branches:
              only: main
      - test:
          filters:
            branches:
              only: main
      - build:
          filters:
            branches:
              only: main
      - deliver:
          filters:
            branches:
              only: main
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: deploy/production
