version: 2.1
executors:
  node-executor:
    docker:
      - image: node:16
  docker-executor:
    docker:
      - image: docker:latest
jobs:
  lint:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    executor: node-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build_db:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker DB Image
          command: docker build -f Dockerfile-db -t your-dockerhub-name/your-db-image-name .
  build_app:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker App Image
          command: docker build -f Dockerfile-app -t your-dockerhub-name/your-app-image-name .
  deliver_db:
    executor: docker-executor
    steps:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push your-dockerhub-name/your-db-image-name
  deliver_app:
    executor: docker-executor
    steps:
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push your-dockerhub-name/your-app-image-name
  deploy:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to AWS
          command: |
            # Here, add commands to deploy to AWS using aws cli or any other tool you're using


workflows:
  version: 2
  build-test-and-deliver:
    jobs:
      - lint:
          filters:
            branches:
              only: main
      - test:
          filters:
            branches:
              only: main
      - build-db:
          filters:
            branches:
              only: main
      - build-app:
          filters:
            branches:
              only: main
      - deliver-db:
          filters:
            branches:
              only: main
      - deliver-app:
          filters:
            branches:
              only: main
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: deploy/production
