version: 2.1
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.2.0
jobs:
  lint:
    executor: 
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  test:
    executor: 
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build:
    executor: 
      name: docker/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker DB Image
          command: docker-compose build
  deliver:
    executor: 
      name: docker/default
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-compose build --push domain314/conint_backend
  deploy:
    executor: 
      name: docker/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy to AWS
          command: |
            # deploy to AWS


workflows:
  version: 2
  build-test-deliver-and-deploy:
    jobs:
      - lint:
          filters:
            branches:
              only: main
      - test:
          requires:
            - lint
          filters:
            branches:
              only: main
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
      - deliver:
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - deliver
          filters:
            branches:
              only: deploy/production
